/* generated by rust_qt_binding_generator */
use libc::{c_char, c_ushort, c_int};
use std::slice;
use std::char::decode_utf16;

use std::sync::Arc;
use std::sync::atomic::{AtomicPtr, Ordering};
use std::ptr::null;

use implementation::*;


#[repr(C)]
pub struct COption<T> {
    data: T,
    some: bool,
}

impl<T> COption<T> {
    #![allow(dead_code)]
    fn into(self) -> Option<T> {
        if self.some {
            Some(self.data)
        } else {
            None
        }
    }
}

impl<T> From<Option<T>> for COption<T>
where
    T: Default,
{
    fn from(t: Option<T>) -> COption<T> {
        if let Some(v) = t {
            COption {
                data: v,
                some: true,
            }
        } else {
            COption {
                data: T::default(),
                some: false,
            }
        }
    }
}


pub enum QString {}

fn set_string_from_utf16(s: &mut String, str: *const c_ushort, len: c_int) {
    let utf16 = unsafe { slice::from_raw_parts(str, to_usize(len)) };
    let characters = decode_utf16(utf16.iter().cloned())
        .map(|r| r.unwrap());
    s.clear();
    s.extend(characters);
}



#[repr(C)]
#[derive(PartialEq, Eq, Debug)]
pub enum SortOrder {
    Ascending = 0,
    Descending = 1,
}

#[repr(C)]
pub struct QModelIndex {
    row: c_int,
    internal_id: usize,
}


fn to_usize(n: c_int) -> usize {
    if n < 0 {
        panic!("Cannot cast {} to usize", n);
    }
    n as usize
}


fn to_c_int(n: usize) -> c_int {
    if n > c_int::max_value() as usize {
        panic!("Cannot cast {} to c_int", n);
    }
    n as c_int
}


pub struct RomListQObject {}

pub struct RomListEmitter {
    qobject: Arc<AtomicPtr<RomListQObject>>,
    new_data_ready: fn(*mut RomListQObject),
}

unsafe impl Send for RomListEmitter {}

impl RomListEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> RomListEmitter {
        RomListEmitter {
            qobject: self.qobject.clone(),
            new_data_ready: self.new_data_ready,
        }
    }
    fn clear(&self) {
        let n: *const RomListQObject = null();
        self.qobject.store(n as *mut RomListQObject, Ordering::SeqCst);
    }
    pub fn new_data_ready(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.new_data_ready)(ptr);
        }
    }
}

#[derive(Clone)]
pub struct RomListList {
    qobject: *mut RomListQObject,
    layout_about_to_be_changed: fn(*mut RomListQObject),
    layout_changed: fn(*mut RomListQObject),
    data_changed: fn(*mut RomListQObject, usize, usize),
    begin_reset_model: fn(*mut RomListQObject),
    end_reset_model: fn(*mut RomListQObject),
    begin_insert_rows: fn(*mut RomListQObject, usize, usize),
    end_insert_rows: fn(*mut RomListQObject),
    begin_move_rows: fn(*mut RomListQObject, usize, usize, usize),
    end_move_rows: fn(*mut RomListQObject),
    begin_remove_rows: fn(*mut RomListQObject, usize, usize),
    end_remove_rows: fn(*mut RomListQObject),
}

impl RomListList {
    pub fn layout_about_to_be_changed(&mut self) {
        (self.layout_about_to_be_changed)(self.qobject);
    }
    pub fn layout_changed(&mut self) {
        (self.layout_changed)(self.qobject);
    }
    pub fn data_changed(&mut self, first: usize, last: usize) {
        (self.data_changed)(self.qobject, first, last);
    }
    pub fn begin_reset_model(&mut self) {
        (self.begin_reset_model)(self.qobject);
    }
    pub fn end_reset_model(&mut self) {
        (self.end_reset_model)(self.qobject);
    }
    pub fn begin_insert_rows(&mut self, first: usize, last: usize) {
        (self.begin_insert_rows)(self.qobject, first, last);
    }
    pub fn end_insert_rows(&mut self) {
        (self.end_insert_rows)(self.qobject);
    }
    pub fn begin_move_rows(&mut self, first: usize, last: usize, destination: usize) {
        (self.begin_move_rows)(self.qobject, first, last, destination);
    }
    pub fn end_move_rows(&mut self) {
        (self.end_move_rows)(self.qobject);
    }
    pub fn begin_remove_rows(&mut self, first: usize, last: usize) {
        (self.begin_remove_rows)(self.qobject, first, last);
    }
    pub fn end_remove_rows(&mut self) {
        (self.end_remove_rows)(self.qobject);
    }
}

pub trait RomListTrait {
    fn new(emit: RomListEmitter, model: RomListList) -> Self;
    fn emit(&mut self) -> &mut RomListEmitter;
    fn row_count(&self) -> usize;
    fn insert_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn remove_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn can_fetch_more(&self) -> bool {
        false
    }
    fn fetch_more(&mut self) {}
    fn sort(&mut self, u8, SortOrder) {}
    fn name(&self, index: usize) -> &str;
}

#[no_mangle]
pub extern "C" fn rom_list_new(
    rom_list: *mut RomListQObject,
    rom_list_new_data_ready: fn(*mut RomListQObject),
    rom_list_layout_about_to_be_changed: fn(*mut RomListQObject),
    rom_list_layout_changed: fn(*mut RomListQObject),
    rom_list_data_changed: fn(*mut RomListQObject, usize, usize),
    rom_list_begin_reset_model: fn(*mut RomListQObject),
    rom_list_end_reset_model: fn(*mut RomListQObject),
    rom_list_begin_insert_rows: fn(*mut RomListQObject, usize, usize),
    rom_list_end_insert_rows: fn(*mut RomListQObject),
    rom_list_begin_move_rows: fn(*mut RomListQObject, usize, usize, usize),
    rom_list_end_move_rows: fn(*mut RomListQObject),
    rom_list_begin_remove_rows: fn(*mut RomListQObject, usize, usize),
    rom_list_end_remove_rows: fn(*mut RomListQObject),
) -> *mut RomList {
    let rom_list_emit = RomListEmitter {
        qobject: Arc::new(AtomicPtr::new(rom_list)),
        new_data_ready: rom_list_new_data_ready,
    };
    let model = RomListList {
        qobject: rom_list,
        layout_about_to_be_changed: rom_list_layout_about_to_be_changed,
        layout_changed: rom_list_layout_changed,
        data_changed: rom_list_data_changed,
        begin_reset_model: rom_list_begin_reset_model,
        end_reset_model: rom_list_end_reset_model,
        begin_insert_rows: rom_list_begin_insert_rows,
        end_insert_rows: rom_list_end_insert_rows,
        begin_move_rows: rom_list_begin_move_rows,
        end_move_rows: rom_list_end_move_rows,
        begin_remove_rows: rom_list_begin_remove_rows,
        end_remove_rows: rom_list_end_remove_rows,
    };
    let d_rom_list = RomList::new(rom_list_emit, model);
    Box::into_raw(Box::new(d_rom_list))
}

#[no_mangle]
pub unsafe extern "C" fn rom_list_free(ptr: *mut RomList) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn rom_list_row_count(ptr: *const RomList) -> c_int {
    to_c_int((&*ptr).row_count())
}
#[no_mangle]
pub unsafe extern "C" fn rom_list_insert_rows(ptr: *mut RomList, row: c_int, count: c_int) -> bool {
    (&mut *ptr).insert_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn rom_list_remove_rows(ptr: *mut RomList, row: c_int, count: c_int) -> bool {
    (&mut *ptr).remove_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn rom_list_can_fetch_more(ptr: *const RomList) -> bool {
    (&*ptr).can_fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn rom_list_fetch_more(ptr: *mut RomList) {
    (&mut *ptr).fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn rom_list_sort(
    ptr: *mut RomList,
    column: u8,
    order: SortOrder,
) {
    (&mut *ptr).sort(column, order)
}

#[no_mangle]
pub unsafe extern "C" fn rom_list_data_name(
    ptr: *const RomList, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.name(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

pub struct SimpleQObject {}

pub struct SimpleEmitter {
    qobject: Arc<AtomicPtr<SimpleQObject>>,
    message_changed: fn(*mut SimpleQObject),
}

unsafe impl Send for SimpleEmitter {}

impl SimpleEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> SimpleEmitter {
        SimpleEmitter {
            qobject: self.qobject.clone(),
            message_changed: self.message_changed,
        }
    }
    fn clear(&self) {
        let n: *const SimpleQObject = null();
        self.qobject.store(n as *mut SimpleQObject, Ordering::SeqCst);
    }
    pub fn message_changed(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.message_changed)(ptr);
        }
    }
}

pub trait SimpleTrait {
    fn new(emit: SimpleEmitter,
        rom_list: RomList) -> Self;
    fn emit(&mut self) -> &mut SimpleEmitter;
    fn message(&self) -> &str;
    fn set_message(&mut self, value: String);
    fn rom_list(&self) -> &RomList;
    fn rom_list_mut(&mut self) -> &mut RomList;
}

#[no_mangle]
pub extern "C" fn simple_new(
    simple: *mut SimpleQObject,
    simple_message_changed: fn(*mut SimpleQObject),
    rom_list: *mut RomListQObject,
    rom_list_new_data_ready: fn(*mut RomListQObject),
    rom_list_layout_about_to_be_changed: fn(*mut RomListQObject),
    rom_list_layout_changed: fn(*mut RomListQObject),
    rom_list_data_changed: fn(*mut RomListQObject, usize, usize),
    rom_list_begin_reset_model: fn(*mut RomListQObject),
    rom_list_end_reset_model: fn(*mut RomListQObject),
    rom_list_begin_insert_rows: fn(*mut RomListQObject, usize, usize),
    rom_list_end_insert_rows: fn(*mut RomListQObject),
    rom_list_begin_move_rows: fn(*mut RomListQObject, usize, usize, usize),
    rom_list_end_move_rows: fn(*mut RomListQObject),
    rom_list_begin_remove_rows: fn(*mut RomListQObject, usize, usize),
    rom_list_end_remove_rows: fn(*mut RomListQObject),
) -> *mut Simple {
    let rom_list_emit = RomListEmitter {
        qobject: Arc::new(AtomicPtr::new(rom_list)),
        new_data_ready: rom_list_new_data_ready,
    };
    let model = RomListList {
        qobject: rom_list,
        layout_about_to_be_changed: rom_list_layout_about_to_be_changed,
        layout_changed: rom_list_layout_changed,
        data_changed: rom_list_data_changed,
        begin_reset_model: rom_list_begin_reset_model,
        end_reset_model: rom_list_end_reset_model,
        begin_insert_rows: rom_list_begin_insert_rows,
        end_insert_rows: rom_list_end_insert_rows,
        begin_move_rows: rom_list_begin_move_rows,
        end_move_rows: rom_list_end_move_rows,
        begin_remove_rows: rom_list_begin_remove_rows,
        end_remove_rows: rom_list_end_remove_rows,
    };
    let d_rom_list = RomList::new(rom_list_emit, model);
    let simple_emit = SimpleEmitter {
        qobject: Arc::new(AtomicPtr::new(simple)),
        message_changed: simple_message_changed,
    };
    let d_simple = Simple::new(simple_emit,
        d_rom_list);
    Box::into_raw(Box::new(d_simple))
}

#[no_mangle]
pub unsafe extern "C" fn simple_free(ptr: *mut Simple) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn simple_message_get(
    ptr: *const Simple,
    p: *mut QString,
    set: fn(*mut QString, *const c_char, c_int),
) {
    let o = &*ptr;
    let v = o.message();
    let s: *const c_char = v.as_ptr() as (*const c_char);
    set(p, s, to_c_int(v.len()));
}

#[no_mangle]
pub unsafe extern "C" fn simple_message_set(ptr: *mut Simple, v: *const c_ushort, len: c_int) {
    let o = &mut *ptr;
    let mut s = String::new();
    set_string_from_utf16(&mut s, v, len);
    o.set_message(s);
}

#[no_mangle]
pub unsafe extern "C" fn simple_rom_list_get(ptr: *mut Simple) -> *mut RomList {
    (&mut *ptr).rom_list_mut()
}
