/* generated by rust_qt_binding_generator */
#include "Bindings.h"

namespace {

    struct option_quintptr {
    public:
        quintptr value;
        bool some;
        operator QVariant() const {
            if (some) {
                return QVariant::fromValue(value);
            }
            return QVariant();
        }
    };
    static_assert(std::is_pod<option_quintptr>::value, "option_quintptr must be a POD type.");

    typedef void (*qstring_set)(QString* val, const char* utf8, int nbytes);
    void set_qstring(QString* val, const char* utf8, int nbytes) {
        *val = QString::fromUtf8(utf8, nbytes);
    }

    struct qmodelindex_t {
        int row;
        quintptr id;
    };
    inline QVariant cleanNullQVariant(const QVariant& v) {
        return (v.isNull()) ?QVariant() :v;
    }
    inline void simpleMessageChanged(Simple* o)
    {
        Q_EMIT o->messageChanged();
    }
}
extern "C" {
    void rom_list_data_name(const RomList::Private*, int, QString*, qstring_set);
    void rom_list_sort(RomList::Private*, unsigned char column, Qt::SortOrder order = Qt::AscendingOrder);

    int rom_list_row_count(const RomList::Private*);
    bool rom_list_insert_rows(RomList::Private*, int, int);
    bool rom_list_remove_rows(RomList::Private*, int, int);
    bool rom_list_can_fetch_more(const RomList::Private*);
    void rom_list_fetch_more(RomList::Private*);
}
int RomList::columnCount(const QModelIndex &parent) const
{
    return (parent.isValid()) ? 0 : 1;
}

bool RomList::hasChildren(const QModelIndex &parent) const
{
    return rowCount(parent) > 0;
}

int RomList::rowCount(const QModelIndex &parent) const
{
    return (parent.isValid()) ? 0 : rom_list_row_count(m_d);
}

bool RomList::insertRows(int row, int count, const QModelIndex &)
{
    return rom_list_insert_rows(m_d, row, count);
}

bool RomList::removeRows(int row, int count, const QModelIndex &)
{
    return rom_list_remove_rows(m_d, row, count);
}

QModelIndex RomList::index(int row, int column, const QModelIndex &parent) const
{
    if (!parent.isValid() && row >= 0 && row < rowCount(parent) && column >= 0 && column < 1) {
        return createIndex(row, column, (quintptr)row);
    }
    return QModelIndex();
}

QModelIndex RomList::parent(const QModelIndex &) const
{
    return QModelIndex();
}

bool RomList::canFetchMore(const QModelIndex &parent) const
{
    return (parent.isValid()) ? 0 : rom_list_can_fetch_more(m_d);
}

void RomList::fetchMore(const QModelIndex &parent)
{
    if (!parent.isValid()) {
        rom_list_fetch_more(m_d);
    }
}
void RomList::updatePersistentIndexes() {}

void RomList::sort(int column, Qt::SortOrder order)
{
    rom_list_sort(m_d, column, order);
}
Qt::ItemFlags RomList::flags(const QModelIndex &i) const
{
    auto flags = QAbstractItemModel::flags(i);
    return flags;
}

QString RomList::name(int row) const
{
    QString s;
    rom_list_data_name(m_d, row, &s, set_qstring);
    return s;
}

QVariant RomList::data(const QModelIndex &index, int role) const
{
    Q_ASSERT(rowCount(index.parent()) > index.row());
    switch (index.column()) {
    case 0:
        switch (role) {
        case Qt::DisplayRole:
        case Qt::UserRole + 0:
            return QVariant::fromValue(name(index.row()));
        }
        break;
    }
    return QVariant();
}

int RomList::role(const char* name) const {
    auto names = roleNames();
    auto i = names.constBegin();
    while (i != names.constEnd()) {
        if (i.value() == name) {
            return i.key();
        }
        ++i;
    }
    return -1;
}
QHash<int, QByteArray> RomList::roleNames() const {
    QHash<int, QByteArray> names = QAbstractItemModel::roleNames();
    names.insert(Qt::UserRole + 0, "name");
    return names;
}
QVariant RomList::headerData(int section, Qt::Orientation orientation, int role) const
{
    if (orientation != Qt::Horizontal) {
        return QVariant();
    }
    return m_headerData.value(qMakePair(section, (Qt::ItemDataRole)role), role == Qt::DisplayRole ?QString::number(section + 1) :QVariant());
}

bool RomList::setHeaderData(int section, Qt::Orientation orientation, const QVariant &value, int role)
{
    if (orientation != Qt::Horizontal) {
        return false;
    }
    m_headerData.insert(qMakePair(section, (Qt::ItemDataRole)role), value);
    return true;
}

extern "C" {
    RomList::Private* rom_list_new(RomList*,
        void (*)(const RomList*),
        void (*)(RomList*),
        void (*)(RomList*),
        void (*)(RomList*, quintptr, quintptr),
        void (*)(RomList*),
        void (*)(RomList*),
        void (*)(RomList*, int, int),
        void (*)(RomList*),
        void (*)(RomList*, int, int, int),
        void (*)(RomList*),
        void (*)(RomList*, int, int),
        void (*)(RomList*));
    void rom_list_free(RomList::Private*);
};

extern "C" {
    Simple::Private* simple_new(Simple*, void (*)(Simple*), RomList*,
        void (*)(const RomList*),
        void (*)(RomList*),
        void (*)(RomList*),
        void (*)(RomList*, quintptr, quintptr),
        void (*)(RomList*),
        void (*)(RomList*),
        void (*)(RomList*, int, int),
        void (*)(RomList*),
        void (*)(RomList*, int, int, int),
        void (*)(RomList*),
        void (*)(RomList*, int, int),
        void (*)(RomList*));
    void simple_free(Simple::Private*);
    void simple_message_get(const Simple::Private*, QString*, qstring_set);
    void simple_message_set(Simple::Private*, const ushort *str, int len);
    RomList::Private* simple_rom_list_get(const Simple::Private*);
};

RomList::RomList(bool /*owned*/, QObject *parent):
    QAbstractItemModel(parent),
    m_d(nullptr),
    m_ownsPrivate(false)
{
    initHeaderData();
}

RomList::RomList(QObject *parent):
    QAbstractItemModel(parent),
    m_d(rom_list_new(this,
        [](const RomList* o) {
            Q_EMIT o->newDataReady(QModelIndex());
        },
        [](RomList* o) {
            Q_EMIT o->layoutAboutToBeChanged();
        },
        [](RomList* o) {
            o->updatePersistentIndexes();
            Q_EMIT o->layoutChanged();
        },
        [](RomList* o, quintptr first, quintptr last) {
            o->dataChanged(o->createIndex(first, 0, first),
                       o->createIndex(last, 0, last));
        },
        [](RomList* o) {
            o->beginResetModel();
        },
        [](RomList* o) {
            o->endResetModel();
        },
        [](RomList* o, int first, int last) {
            o->beginInsertRows(QModelIndex(), first, last);
        },
        [](RomList* o) {
            o->endInsertRows();
        },
        [](RomList* o, int first, int last, int destination) {
            o->beginMoveRows(QModelIndex(), first, last, QModelIndex(), destination);
        },
        [](RomList* o) {
            o->endMoveRows();
        },
        [](RomList* o, int first, int last) {
            o->beginRemoveRows(QModelIndex(), first, last);
        },
        [](RomList* o) {
            o->endRemoveRows();
        }
)),
    m_ownsPrivate(true)
{
    connect(this, &RomList::newDataReady, this, [this](const QModelIndex& i) {
        this->fetchMore(i);
    }, Qt::QueuedConnection);
    initHeaderData();
}

RomList::~RomList() {
    if (m_ownsPrivate) {
        rom_list_free(m_d);
    }
}
void RomList::initHeaderData() {
    m_headerData.insert(qMakePair(0, Qt::DisplayRole), QVariant("name"));
}
Simple::Simple(bool /*owned*/, QObject *parent):
    QObject(parent),
    m_romList(new RomList(false, this)),
    m_d(nullptr),
    m_ownsPrivate(false)
{
}

Simple::Simple(QObject *parent):
    QObject(parent),
    m_romList(new RomList(false, this)),
    m_d(simple_new(this,
        simpleMessageChanged, m_romList,
        [](const RomList* o) {
            Q_EMIT o->newDataReady(QModelIndex());
        },
        [](RomList* o) {
            Q_EMIT o->layoutAboutToBeChanged();
        },
        [](RomList* o) {
            o->updatePersistentIndexes();
            Q_EMIT o->layoutChanged();
        },
        [](RomList* o, quintptr first, quintptr last) {
            o->dataChanged(o->createIndex(first, 0, first),
                       o->createIndex(last, 0, last));
        },
        [](RomList* o) {
            o->beginResetModel();
        },
        [](RomList* o) {
            o->endResetModel();
        },
        [](RomList* o, int first, int last) {
            o->beginInsertRows(QModelIndex(), first, last);
        },
        [](RomList* o) {
            o->endInsertRows();
        },
        [](RomList* o, int first, int last, int destination) {
            o->beginMoveRows(QModelIndex(), first, last, QModelIndex(), destination);
        },
        [](RomList* o) {
            o->endMoveRows();
        },
        [](RomList* o, int first, int last) {
            o->beginRemoveRows(QModelIndex(), first, last);
        },
        [](RomList* o) {
            o->endRemoveRows();
        }
)),
    m_ownsPrivate(true)
{
    m_romList->m_d = simple_rom_list_get(m_d);
    connect(this->m_romList, &RomList::newDataReady, this->m_romList, [this](const QModelIndex& i) {
        this->m_romList->fetchMore(i);
    }, Qt::QueuedConnection);
}

Simple::~Simple() {
    if (m_ownsPrivate) {
        simple_free(m_d);
    }
}
QString Simple::message() const
{
    QString v;
    simple_message_get(m_d, &v, set_qstring);
    return v;
}
void Simple::setMessage(const QString& v) {
    simple_message_set(m_d, reinterpret_cast<const ushort*>(v.data()), v.size());
}
const RomList* Simple::romList() const
{
    return m_romList;
}
RomList* Simple::romList()
{
    return m_romList;
}
